### ISSUE TITLE
CentOS: Typelib file for namespace 'Vips' (any version) not found (GLib::Error)

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#104]
Script for gem "ruby-vips", "1.0.3" that works on Mac OS after:
```bash
ARCHFLAGS="-arch x86_64" gem install glib2 -v '3.0.8'
ARCHFLAGS="-arch x86_64" PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig gem install gobject-introspection -v '3.0.8'
```
refuses to work on CentOS after
```bash
sudo yum install glib2-devel
sudo yum install gobject-introspection-devel
```
saying this:
```bash
myuser$ bundle exec ruby myscript.rb 
Unable to load Vips
  Check that the vips library has been installed and is
  on your library path.
  Check that the typelib `Vips-8.0.typelib` has been 
  installed, and that it is on your GI_TYPELIB_PATH.
/home/myuser/.gem/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'Vips' (any version) not found (GLib::Error)
```
Should I specify GI_TYPELIB_PATH variable? What should it equal to?

UPD: `GI_TYPELIB_PATH=/usr/lib64/girepository-1.0` has no effect.
UPD2: ok, seems like I have to actually install the vips. Compiling...
```bash
mysudoer$ sudo yum -y install libxml2-devel
mysudoer$ ./configure
mysudoer$ make
mysudoer$ sudo make install    # without sudo this was throwing an error about inabiiity to mkdir /usr/local...smth
mysudoer$ make check

FAIL: test_formats.sh
=====================
VipsForeignLoad: "/home/mysudoer/vips-8.4.5/test/images/йцук.jpg" is not a known file format

FAIL: test_seq.sh
=================
building huge test PNG image ... VipsForeignLoad: "/home/mysudoer/vips-8.4.5/test/images/йцук.jpg" is not a known file format
ok
testing vipsthumbnail ... /home/mysudoer/vips-8.4.5/tools/.libs/lt-vipsthumbnail: unable to thumbnail /home/mysudoer/vips-8.4.5/test/tmp-19569/huge.png
VipsForeignLoad: file "/home/mysudoer/vips-8.4.5/test/tmp-19569/huge.png" not found
vipsthumbnail failed in basic mode
```
but
```bash
Package libjpeg-turbo-1.2.90-5.el7.x86_64 already installed and latest version
Package 2:libpng-1.5.13-7.el7_2.x86_64 already installed and latest version
```
UPD3: installing `-devel` versions of both libraries didn't have any effect.
And about ruby script (added /usr/local/bin to $PATH):
```bash
myuser$ vips --version
vips-8.4.5-Fri Apr  7 20:00:01 UTC 2017
myuser$ GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0 bundle exec ruby myscript.rb 

/home/myuser/.gem/gems/ruby-vips-1.0.3/lib/vips.rb: line 120
   (null)-WARNING **:Failed to load shared library 'libvips.so.42' referenced by the typelib: libvips.so.42: cannot open shared object file: No such file or directory
Unable to load Vips
  Check that the vips library has been installed and is
  on your library path.
  Check that the typelib `Vips-8.0.typelib` has been 
  installed, and that it is on your GI_TYPELIB_PATH.
/home/myuser/.gem/gems/ruby-vips-1.0.3/lib/vips.rb:120:in `invoke': Could not locate vips_init: libvips.so.42: cannot open shared object file: No such file or directory (GLib::Error)
```

**Comment by jcupitt** [comment]
Hello, it's looking for the file `Vips-8.0.typelib`, you need to have the enclosing directory on your `GI_TYPELIB_PATH`. For example, I see:

```
john@kiwi:~$ echo $GI_TYPELIB_PATH 
/home/john/vips/lib/girepository-1.0:
john@kiwi:~$ ls /home/john/vips/lib/girepository-1.0
Vips-8.0.typelib
```

If you put the typelib file in the standard directory for your system (which the package should probably do), you don't need to set the environment variable. There are some more notes here:

http://www.rubydoc.info/gems/ruby-vips/1.0.4/Vips

Perhaps they should be on the start page of the docs.

If there's no CentOS package with the typelib, you'll need to build yourself from source. It needs libvips 8.2 or later.

**Comment by jcupitt** [comment]
Oh hang on, sorry.

Yes, you need the devel versions of libjpeg and friends. Check the output of libvips configure carefully. There's a long list of yes/no at the end, make sure you have yeses where you need them.

Your ruby won't load libraries from `/usr/local/lib` (which I guess is where you have `libvips.so`) by default, this is for security.

You can either configure your whole system to load libraries from there by adding a rule to `/etc/ld.so.conf`, or you can set the env var `LD_LIBRARY_PATH` to point at that directory. I would recommend setting the library path. I have:

```
john@kiwi:~$ echo $LD_LIBRARY_PATH 
/home/john/vips/lib:
john@kiwi:~$ ls /home/john/vips/lib
girepository-1.0  libvipsCC.so.42      libvips-cpp.so.42      libvips.so.42.7.2
libvips.a         libvipsCC.so.42.7.2  libvips-cpp.so.42.7.2  pkgconfig
libvipsCC.a       libvips-cpp.a        libvips.la             python2.7
libvipsCC.la      libvips-cpp.la       libvips.so
libvipsCC.so      libvips-cpp.so       libvips.so.42
```

**Comment by Nakilon** [comment]
With `LD_LIBRARY_PATH=/usr/local/lib GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0` I now get next error:
```
/home/myuser/.gem/gems/ruby-vips-1.0.3/lib/vips/image.rb:448:in `new_from_file': VipsForeignLoad: "images/2b714fb8cdf3078f57ed837916b71414" is not a known file format (Vips::Error)
```
Seems like it's the same that I get in tests:
```bash
mysudoer@lab-2 vips-8.4.5]$ LD_LIBRARY_PATH=/usr/local/lib GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0 make check
```
```bash
FAIL: test_formats.sh
=====================

VipsForeignLoad: "/home/mysudoer/vips-8.4.5/test/images/йцук.jpg" is not a known file format

FAIL: test_seq.sh
=================

building huge test PNG image ... VipsForeignLoad: "/home/mysudoer/vips-8.4.5/test/images/йцук.jpg" is not a known file format
ok
testing vipsthumbnail ... /home/mysudoer/vips-8.4.5/tools/.libs/lt-vipsthumbnail: unable to thumbnail /home/mysudoer/vips-8.4.5/test/tmp-9482/huge.png
VipsForeignLoad: file "/home/mysudoer/vips-8.4.5/test/tmp-9482/huge.png" not found
vipsthumbnail failed in basic mode
```

**Comment by jcupitt** [comment]
That's good, you just need to get configure to find your jpeg headers now.

I would look at `config.log` in a text editor and search for jpeg. You should see all the tests it ran to try to locate the headers, to try compiling a small test program, and to try linking it. Hopefully it'll be clear what went wrong or what it failed to find.

You can use the configure arguments `--with-jpeg-includes` and `--with-jpeg-libraries` to point configure in the right direction. There are some notes in the install instructions:

http://jcupitt.github.io/libvips/install.html#optional-dependencies

You'll need something similar for libpng. Unfortunately, centos does not package pkg-config files, so it has to do the same search for headers nonsense.

**Comment by Nakilon** [comment]
I'm not good in compiling. After some try to run ./configure and make with those two variables now even after reunpacking the .tar.gz I get this:
```
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/libpng15 -I/usr/include/glib-2.0 -g -O2 -MT vips2jpeg.lo -MD -MP -MF .deps/vips2jpeg.Tpo -c vips2jpeg.c  -fPIC -DPIC -o .libs/vips2jpeg.o
In file included from vips2jpeg.c:148:0:
jpeg.h:80:32: error: unknown type name ‘ExifData’
 int vips__set_exif_resolution( ExifData *ed, VipsImage *im );
                                ^
make[3]: *** [vips2jpeg.lo] Error 1
make[3]: Leaving directory `/home/nakilon/vips-8.4.5/libvips/foreign'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/nakilon/vips-8.4.5/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/nakilon/vips-8.4.5'
make: *** [all] Error 2
```

**Comment by Nakilon** [comment]
Had to also install expat-devel.x86_64
```
# TOTAL: 4
# PASS:  4
```
And gem is working! Thank you!

**Comment by Nakilon** [comment]
P.S.: after installing giflib you have to recompile.

**Comment by Nakilon** [comment]
Oh crap, I've installed Ruby 2.1 (for memory debugging) via rbenv and set `GEM_HOME=./gems21` but now after `./gems21/bin/bundle install` I see this error again:
```
myuser$  LD_LIBRARY_PATH=/usr/local/lib
myuser$  GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0
myuser$  ./gems21/bin/bundle exec ruby scraper.rb 
```
```
Unable to load Vips
  Check that the vips library has been installed and is
  on your library path.
  Check that the typelib `Vips-8.0.typelib` has been
  installed, and that it is on your GI_TYPELIB_PATH.
.../gems21/gems/gobject-introspection-3.0.8/lib/gobject-introspec
tion/loader.rb:37:in `require': Typelib file for namespace 'Vips' (any version) not found (GLib::Error)
        from .../gems21/gems/gobject-introspection-3.0.8/lib/gobj
ect-introspection/loader.rb:37:in `load'
```

**Comment by Nakilon** [comment]
JFYI: With version 8.5.8 on another CentOS the `./configure` said:
```
gobject introspection:                  no
```
but vips was compiled and the gem works fine. So fine that even LD_ and GI_ env variables were needed only for `./configure` and no need of them while running Ruby program like I had in previous case.

So the full instruction is:
```
sudo yum -y install glib2-devel gobject-introspection-devel
sudo yum -y install libpng-devel libjpeg-devel
sudo yum -y install libexif-devel expat-devel.x86_64
ldconfig -p | grep gobject
# should show paths
```
```
LD_LIBRARY_PATH=/lib64 GI_TYPELIB_PATH=/lib64/girepository-1.0 ./configure
make
sudo make install
make check
# should pass 4/4 tests
```

**Comment by jcupitt** [comment]
I've rewritten the gem. Version 2 and later just need the libvips shared library, nothing else. 

gobject-introspection was making installation too difficult :(
