### ISSUE TITLE
vips 8.5, 8.6, Could not open library 'libglib-2.0-0.dll'

### ISSUE THREAD

**Issue by nvoynov** [jcupitt/ruby-vips#151]
Hi,

I'm under win10 and I'm trying to do some staff with image by ruby-vips. I downloaded version 8.6, unzip and wrote path to it in PATH variable, created a new gem, added gem 'ruby-vips' to Gemfile and done bundle command successfully.

After that I try to load image `Vips::Image.new_from_file(@image_file)` and have the next error (later I changed 8.6 to 8.5 but result still the same)

```
C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libglib-2.0-0.dll':  (LoadError)
```

The reason is that I want to calculate few kinds of passe-partouts for my photograph and write to image file to assess it by eye. I'm an absolute newbie in image processing so I will appreciate any help with my task. I know all the calculations that I need, but 
* how to create a new image for passe-partouts?
* how to fill background to certain color?
* how to scale target image form file and inscribe it to created image of passe-partouts?

**Comment by jcupitt** [comment]
Hello @nvoynov,

Did you include `bin` in the `PATH` setting? For example, if you unzip vips to `D:\something\vips-8.6.1`, you must add `D:\something\vips-8.6.1\bin` to your `PATH`.

To test it is working correctly, open a command window and type `vips`. You should see something like:

```
$ vips
Usage:
  vips [OPTION…] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program

Help Options:
  -h, --help                    Show help options

Application Options:
  -l, --list=BASE-NAME          list objects
  -p, --plugin=PLUGIN           load PLUGIN
  -v, --version                 print version
  --vips-concurrency=N          evaluate with N concurrent threads
  --vips-progress               show progress feedback
... etc.
```

I'll make you a demo passe-partout script.

**Comment by nvoynov** [comment]
Of course I added `C:\vips-XXX\bin` to PATH and I can see it through `$ echo %path%`. Unfortunately I cannot check output of `$ vips` command right now, but I'll try the command when I get home. And I'll try some earlier vips releases down to 8.2 when it fails again.

Thank you for help! Especially for the featured demo script.

**Comment by jcupitt** [comment]
I've used at least vips 8.5 and 8.6 with ruby-vips on a win7 machine, so I'd think it would work on win10. Anyway, I would double-check the `PATH` setting.

**Comment by jcupitt** [comment]
Here's a demo passe program:

```ruby
require 'vips'

shadow_colour = [50, 50, 50] 
light_colour = [100, 100, 100]
passe_colour = [100, 70, 130]
bezel_size = 20
passe_size = 500
passe_top = 500
passe_bottom = 700

image = Vips::Image.new_from_file ARGV[0], access: :sequential

texture = Vips::Image.new_from_file ARGV[1]

# make the mask for the bezel
# a bit larger than the image, with a line from bottom left to top right
xyz = Vips::Image.xyz image.width + 2 * bezel_size, 
        image.height + 2 * bezel_size
bezel_mask = xyz[0] / xyz.width < (-xyz[1] / xyz.height) + 1

# generate a corner mask for the bezel ... a 45-degree slope
corner_size = [bezel_mask.width, bezel_mask.height].min / 2
xyz = Vips::Image.xyz corner_size, corner_size
bezel_corner_mask = xyz[0] < -xyz[1] + xyz.height

# and paste in the corner masks
bezel_mask = bezel_mask.insert bezel_corner_mask, 
        0, bezel_mask.height - bezel_corner_mask.height
bezel_mask = bezel_mask.insert bezel_corner_mask, 
        bezel_mask.width - bezel_corner_mask.width, 0

# use the mask to generate the bezel RGB image
bezel = bezel_mask.ifthenelse shadow_colour, light_colour

# paste the image into the bezel
image = bezel.insert image, bezel_size, bezel_size

# final image size
image_width = image.width + 2 * passe_size
image_height = image.height + passe_top + passe_bottom

# tile and crop the texture to the requested size
passe = texture.replicate 1 + image_width / texture.width,
        1 + image_height / texture.height 
passe = passe.crop 0, 0, image_width, image_height

# and paste into the mount
image = passe.insert image, passe_size, passe_top 

image.write_to_file ARGV[2]
```

Run like this:

```
$ ruby passe.rb ~/pics/theo.jpg ~/pics/leather.jpeg x.jpg
```

And it'll read the portrait `theo.jpg` and the texture file `leather.jpg` and write the image `x.jpg`. I see:

![tn_x](https://user-images.githubusercontent.com/580843/35442079-d255e72a-029d-11e8-9bfa-a56212392e5c.jpg)

**Comment by nvoynov** [comment]
Excellent! Thank you so much @jcupitt.
I will publish my results here when I cope with paths.

**Comment by nvoynov** [comment]
vips from console works, but ruby script doesn't
maybe sth wrong with `ffi` gem version?

```
C:\Users\User\Documents\ruby\mat>bundle exec ruby lib/mat/frame.rb
C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libglib-2.0-0.dll':  (LoadError)
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ruby-vips-2.0.9/lib/vips.rb:28:in `<module:GLib>'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ruby-vips-2.0.9/lib/vips.rb:13:in `<top (required)>'
        from lib/mat/frame.rb:3:in `require'
        from lib/mat/frame.rb:3:in `<main>'

C:\Users\User\Documents\ruby\mat>vips -v
vips-8.5.8-Tue Aug 22 18:30:00 BST 2017

C:\Users\User\Documents\ruby\mat>bundle show
Gems included by the bundle:
  * bundler (1.13.6)
  * ffi (1.9.18)
  * mat (0.1.0)
  * minitest (5.11.2)
  * rake (10.5.0)
  * ruby-vips (2.0.9)
```

**Comment by nvoynov** [comment]
```
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

$vips -v
vips-8.5.8-Tue Aug 22 18:30:00 BST 2017

$ ruby -e "require 'vips'"
C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libglib-2.0-0.dll':  (LoadError)
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.18-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ruby-vips-2.0.9/lib/vips.rb:28:in `<module:GLib>'
        from C:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/ruby-vips-2.0.9/lib/vips.rb:13:in `<top (required)>'
        from C:/ruby/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/ruby/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/ruby/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from -e:1:in `<main>'
```

**Comment by nvoynov** [comment]
the same situation under ruby 2.4

```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

$ vips -v
vips-8.6.1-Wed Jan  3 08:34:04 UTC 2018

$ gem install ruby-vips
Fetching: ffi-1.9.18-x64-mingw32.gem (100%)
Successfully installed ffi-1.9.18-x64-mingw32
Fetching: ruby-vips-2.0.9.gem (100%)
Successfully installed ruby-vips-2.0.9
Parsing documentation for ffi-1.9.18-x64-mingw32
Installing ri documentation for ffi-1.9.18-x64-mingw32
Parsing documentation for ruby-vips-2.0.9
Installing ri documentation for ruby-vips-2.0.9
Done installing documentation for ffi, ruby-vips after 5 seconds
2 gems installed

$ ruby -e "require 'vips'"
C:/ruby/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.9.18-x64-mingw32/lib/ffi/library.rb:147:in `b (LoadError)lib': Could not open library 'libglib-2.0-0.dll': �� ������ ��������� ������.
        from C:/ruby/Ruby24/lib/ruby/gems/2.4.0/gems/ffi-1.9.18-x64-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/ruby/Ruby24/lib
```

**Comment by jcupitt** [comment]
Hello again, sorry, this dropped off my radar.

I remembered this issue from last year:

https://github.com/jcupitt/ruby-vips/issues/115#issuecomment-317198695

Could you try also setting the environment variable `RUBY_DLL_PATH`? It might help.

**Comment by jcupitt** [comment]
I'll add a note to the README. Which Windows Ruby binary did you use?

**Comment by nvoynov** [comment]
I'm not sure there is a point for README. Just realized that my Ruby 2.2.X binary is 32bit, but vips installation is 64bit and it combination does not work ... just the way as I explained it for myself :)

**Comment by larskanis** [comment]
Just to let you know: I added libvips to MSYS2 MINGW packages, so that install on Windows RubyInstaller is pretty easy now:
```cmd
ridk exec pacman -S mingw-w64-x86_64-libvips
gem inst ruby-vips
```
Or `-i686-` for 32 bit ruby. There's no need to set `RUBY_DLL_PATH` that way.
