### ISSUE TITLE
SegFault when reading UTF-8 encoded stream

### ISSUE THREAD

**Issue by raimondasv** [jcupitt/ruby-vips#169]
macOs High Sierra
vips version: 8.5.6
Ruby version: 2.4.1 to 2.5.1
ruby-vips version: 2.0.9

Steps to reproduce - run this code
```
require 'vips'
require 'open-uri'

puts Vips::VERSION, RUBY_VERSION

remote = open('https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png').read
stream = remote.force_encoding('UTF-8')

Vips::Image.new_from_buffer(stream, '')
```
Results in 

```
2.0.9
2.4.1
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/gvalue.rb:140: [BUG] Segmentation fault at 0x0000010fd17000
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0076 e:000075 CFUNC  :write_bytes
c:0009 p:0718 s:0071 e:000070 METHOD /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/gvalue.rb:140
c:0008 p:0066 s:0061 E:0006f0 METHOD /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/object.rb:169
c:0007 p:0126 s:0053 e:000052 METHOD /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:154
c:0006 p:0058 s:0044 e:000043 BLOCK  /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:314 [FINISH]
c:0005 p:---- s:0037 e:000036 CFUNC  :each_index
c:0004 p:0333 s:0033 E:001d08 METHOD /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:309
c:0003 p:0075 s:0016 e:000015 METHOD /Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/image.rb:285
c:0002 p:0083 s:0008 E:0009d0 EVAL   crash.rb:9 [FINISH]
c:0001 p:0000 s:0003 E:000b20 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
crash.rb:9:in `<main>'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/image.rb:285:in `new_from_buffer'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:309:in `call'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:309:in `each_index'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:314:in `block in call'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/operation.rb:154:in `set'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/object.rb:169:in `set'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/gvalue.rb:140:in `set'
/Users/host/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby-vips-2.0.9/lib/vips/gvalue.rb:140:in `write_bytes'

-- Machine register context ------------------------------------------------
 rax: 0x000000010fcf1000 rbx: 0x0000000000027125 rcx: 0x0000000000001125
 rdx: 0x0000000000027125 rdi: 0x000000010fd17000 rsi: 0x000000010de34000
 rbp: 0x00007ffee2280f40 rsp: 0x00007ffee2280f40  r8: 0x00007f8ffd969468
  r9: 0x000000010dea98f0 r10: 0x00007f8fffc0a800 r11: 0x0000000001ee3000
 r12: 0x0000000000000000 r13: 0x000000010fcf1000 r14: 0x00007f8fffc572a0
 r15: 0x00007f8ffd95ba98 rip: 0x00007fff54a03f49 rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010db4d268 rb_vm_bugreport + 136
1   ruby                                0x000000010d9e530e rb_bug_context + 510
2   ruby                                0x000000010dac8918 sigsegv + 72
3   libsystem_platform.dylib            0x00007fff54a00f5a _sigtramp + 26
4   libsystem_platform.dylib            0x00007fff54a03f49 _platform_memmove$VARIANT$Haswell + 41
```

**Comment by Nakilon** [comment]
There was a pull request recently that is probably related: https://github.com/jcupitt/ruby-vips/pull/163

Personally I agree with:

> This is arguably user error: you must never load binary files as UTF-8 strings

**Comment by jcupitt** [comment]
Hello, yes, this is fixed in git master ruby-vips. 

We ought to put out a new version: a few fixes have built up now.

**Comment by raimondasv** [comment]
Thank you @Nakilon @jcupitt

**Comment by jcupitt** [comment]
OK, pushed 2.0.10 with this fix.
